# Generated by Django 2.0.3 on 2018-10-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incart',
            name='test',
        ),
    ]
