# Generated by Django 2.0.3 on 2018-10-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_incart_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incart',
            old_name='produuct',
            new_name='product',
        ),
    ]
